id: AF595C3FA
base_file: f842A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:53:11.912662
  last_modified_at: 2022-06-19 17:53:11.912666
