id: AF595C3FA
base_file: f0311.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:53:11.911112
  last_modified_at: 2022-06-19 17:53:11.911119
