id: AF595C3FA
base_file: fB24D.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:53:11.914042
  last_modified_at: 2022-06-19 17:53:11.914045
